name: Vapor

on:
  push:
    branches: [ "master" ]

jobs:
  ubuntu_test:
    name: Ubuntu Build & Test
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        container:
          - swift:5.7.3-jammy
          - swift:5.8.0-jammy
          - swiftlang/swift:nightly-5.9-jammy
    container: ${{ matrix.container }}
    steps:
    - uses: actions/checkout@v3
    - name: Build • Debug
      run: swift build
    - name: Test • Debug
      run: swift test
    - name: Build • Release
      run: swift build -c release
    - name: Test • Release
      run: swift test -c release -Xswiftc -enable-testing
